# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CJMLE_linear <- function(response, nonmis_ind, theta0, A0, Q, sigma_square, C, tol, parallel) {
    .Call('_ECV_CJMLE_linear', PACKAGE = 'ECV', response, nonmis_ind, theta0, A0, Q, sigma_square, C, tol, parallel)
}

confirm_CJMLE_poisson_cpp <- function(response, nonmis_ind, theta0, A0, Q, C, tol = 1e-4) {
    .Call('_ECV_confirm_CJMLE_poisson_cpp', PACKAGE = 'ECV', response, nonmis_ind, theta0, A0, Q, C, tol)
}

